### PR TITLE
Install the Omnibus RPM twice

### PR DESCRIPTION
**Pull request by joshk0**
Certain very old versions of Chef (up until 10.22 or perhaps later)
unconditionally deleted the symlinks to the Chef tools in /usr/bin on
removal. Unfortunately, upgrade involves removal, so upgrading Chef
would trash the symlinks permanently as post-removal scripts are only
run AFTER the post-install script of the new package.

The easiest and most painless workaround to this, to allow people to use
omnibus_updater to upgrade older Chef installs, is simply to run the
Chef install twice. The first run trashes the symlinks going from (bad
version) -> (hopefully fixed new version.) The second run does a no-op
install from (new version) -> (new version). With no cursed version
being involved, the symlinks are deployed and then not deleted by the
post-removal script.

### CODE REVIEW

**Comment by luckymike** [comment]
Please target the Develop branch. Thank you!

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by joshk0** [comment]
@luckymike, I don't work with Chef anymore. Perhaps a ticket could be created for the next person to take up the torch on this.

**Comment by tas50** [comment]
This issue has been solved in the new chef_client_updater cookbook. I'm going to close this issue out here since we've deprecated this cookbook in favor of the new method. We believe it provides a much better experience and encourage everyone to try it out.

**Pull request closed without merging**
